version: '3.8'

networks:
  messagebroker_network:
    driver: bridge

services:
  messagebroker.server:
    image: messagebroker.server
    build:
      context: .
      dockerfile: MessageBroker.Server/Dockerfile
    depends_on:
      - mongo
      - kafka
    environment:
      KAFKA_SERVERS: kafka:9092 # Переменная среды для адреса Kafka
    ports:
      - "5000:5000" # Пример порта, который может быть использован сервером
    networks:
      - messagebroker_network

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
    ports:
      - "27017:27017"
    networks:
      - messagebroker_network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123
      ME_CONFIG_MONGODB_URL: mongodb://root:123@mongo:27017/ 
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongo
    networks:
      - messagebroker_network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - messagebroker_network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092 # Протокол для входящих соединений
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092 # В Docker сети Kafka будет доступна по имени "kafka"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 
      KAFKA_MESSAGE_MAX_BYTES: 200000000 
      KAFKA_REPLICA_FETCH_MAX_BYTES: 200000000
    networks:
      - messagebroker_network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080" 
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092 
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka
    networks:
      - messagebroker_network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "8000:8000" 
    environment:
      OLLAMA_CONFIG_PATH: /app/config/config.yaml 
    volumes:
      - ./ollama/config:/app/config 
    depends_on:
      - mongo
      - kafka
    networks:
      - messagebroker_network
